### ISSUE TITLE
Add AFOLU unit label

### ISSUE THREAD

**Issue by nadams-ei** [Epic-Institute/data-explorer#61]

**Comment by nadams-ei** [comment]
[% of Max Extent] for Nitrogen Fertilizer Management, [Mha] for everything else

If we aren't yet able to switch unit labels depending on the subvertical being shown, and/or show multiple unit labels, we can drop the Nitrogen Fertilizer Management subvertical from the data explorer until we can figure it out.

**Comment by fbecerra-epic** [comment]
I don't think we can use dynamic labels for units in the way it is structured right now -- We'll have to figure something out. As a temporary fix I'm just using [Mha] for everything, including Nitrogen Fertilizer Management
