### ISSUE TITLE
Fix stack order of AFOLU emissions stacked area charts

### ISSUE THREAD

**Issue by nadams-ei** [Epic-Institute/data-explorer#78]
In order for these charts to display correctly, all negative emissions products should be stacked above positive emissions products. See Fig 9a of PD21 for an example, or figures here: https://epic-institute.github.io/positive-disruption/charts/output-emissions.html

**Comment by fbecerra-epic** [comment]
@nadams-ei this should be fixed now, but do you mind giving me an example where we should see a graph like the one from that link? E.g., what should I select (or group by) to have a plot like that?

**Comment by nadams-ei** [comment]
Here is how to recreate the second chart from the link I shared:

- Output: Emissions
- Region: World
- Scenario: Pathway
- Date: 2010-2100
- Sector: Agriculture
- Group By: Product

**Comment by fbecerra-epic** [comment]
Thank you! Will look into it.
