### ISSUE TITLE
Add section that further defines selected Products and Flows

### ISSUE THREAD

**Issue by nadams-ei** [Epic-Institute/data-explorer#86]

**Comment by nadams-ei** [comment]
We have definitions for each product and flow (~1-5 sentences for each). They are currently spread across a couple documents, but can be easily combined into a single file.

Energy subverticals: IEA_Product_Definitions.csv and IEA_Flow_Definitions.csv
AFOLU subverticals: Epic's [github wiki](https://github.com/Epic-Institute/positive-disruption/wiki/Positive-Disruption-Model-Supplemental-Information#4-agriculture-forestry-and-other-land-use-afolu)
Additional emissions: Epic's [github wiki](https://github.com/Epic-Institute/positive-disruption/wiki/Positive-Disruption-Model-Supplemental-Information#5-additional-emissions)

It would be helpful to make a space where these can be displayed or users can search this.

**Comment by fbecerra-epic** [comment]
I added a note to the description for sectors, products, definitions, etc, and I added a link to the GitHub's wiki, which I think is where all that information should be. Does that work for you?

**Comment by nadams-ei** [comment]
I was thinking it would be helpful to make these even easier to view/search. E.g. in the lower left quadrant of the Data Explorer, or as a popup note next to each product and flow in the 'Graph Options' dropdown. I'm open to any other options you might come up with.

**Comment by fbecerra-epic** [comment]
A popup note might be a good option. Do you mind pointing me to the location of the file with all those descriptions, please?

**Comment by nadams-ei** [comment]
Sounds good, as long as it's not too difficult to implement, in which case I'd be fine leaving this open until another option presents itself. Otherwise, see below

- Energy subverticals: 
-- [IEA_Product_Definitions.csv](https://github.com/Epic-Institute/data-explorer/files/10771815/IEA_Product_Definitions.csv)
-- [IEA_Flow_Definitions.csv](https://github.com/Epic-Institute/data-explorer/files/10771816/IEA_Flow_Definitions.csv)
- AFOLU subverticals: Epic's [github wiki](https://github.com/Epic-Institute/positive-disruption/wiki/Positive-Disruption-Model-Supplemental-Information#4-agriculture-forestry-and-other-land-use-afolu), a 'Definition' is listed under each subvertical section.
- Additional emissions: This is going to take some tracking down, so until I get this to you, you can leave these blank
